server.port: 8081
spring:
  jpa:
    show-sql: true
    hibernate.ddl-auto: none
spring.datasource.url: jdbc:postgresql://localhost:5432/crm-project
spring.datasource.username: postgres
spring.datasource.password: admin
